### ISSUE TITLE
Travis scripts TODOs

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#13]
- [x] Linux tests
- [x] Debug/Release mode
- [x] a minimal + a maximal set-up (dependency-wise)? (https://github.com/gnudatalanguage/gdl/pull/237)
- [x] Python module build (see also https://github.com/gnudatalanguage/gdl/issues/8)
- [x] clang
- [x] intel compiler? (https://github.com/nemequ/icc-travis)
- [ ] 32-bit builds? (https://github.com/travis-ci/travis-ci/issues/5770)
- [ ] valgrind
- [ ] making pytests tests part of the coverage report
- [ ] headless GUI tests using a framebuffer? (https://docs.travis-ci.com/user/gui-and-headless-browsers/)
- [ ] Werror for the compiler ?
- [ ] Werror for CMake
- [ ] Windows cross-compilation (e.g. https://github.com/starius/battleship)

Tests that were disabled on Travis as failing at the time of SF->github migration:
- [ ] test_bytscl.pro
- [ ] test_dicom.pro
- [ ] test_fft_leak.pro (https://github.com/gnudatalanguage/gdl/issues/147)
- [ ] test_file_delete.pro (https://github.com/gnudatalanguage/gdl/issues/148)
- [ ] test_file_search.pro 
- [x] test_finite.pro (SIGN kw on OSX? - see https://sourceforge.net/p/gnudatalanguage/bugs/482/)
- [ ] test_fix.pro (https://github.com/gnudatalanguage/gdl/issues/149)
- [ ] test_formats.pro (https://github.com/gnudatalanguage/gdl/issues/144)
- [ ] test_image_statistics.pro (https://github.com/gnudatalanguage/gdl/issues/188)
- [ ] test_make_dll.pro
- [x] test_modulo.pro 
- [ ] test_n_tags.pro (https://github.com/gnudatalanguage/gdl/issues/150)
- [ ] test_obj_isa.pro (https://github.com/gnudatalanguage/gdl/issues/151)
- [ ] test_obj_new.pro
- [x] test_parse_url.pro (https://github.com/gnudatalanguage/gdl/issues/153)
- [ ] test_plot_ranges.pro
- [ ] test_resolve_routine.pro (https://github.com/gnudatalanguage/gdl/issues/146)
- [ ] test_rounding.pro (https://github.com/gnudatalanguage/gdl/issues/154)
- [ ] test_step.pro
- [ ] test_simplex.pro
- [x] test_tictoc.pro
- [x] test_total.pro (https://github.com/gnudatalanguage/gdl/issues/155)
- [ ] test_typename.pro
- [ ] test_wait.pro (#413)
